### ISSUE TITLE
Warning stuck

### ISSUE THREAD

**Issue by cyan** [starfi5h/DSP_Mod_Support#2] opened 2023-01-21 22:51 UTC
Hi,
i've tried to locate somebuilding said to not be connected to the power grid and instead of pointing to a factory, the warning is stuck in the middle of the planet, tried on another planet and the same result and it show a white square in the warning windows on top of the screen instead of an icon.
i tried the clear all button but it didn't work, even after that i could still use the mod to locate empty miners and everything was working fine, except for the white squares still present (even if i run the game without mods).

if you have any idea how to remove those warnings so i could continue to use this mod (while avoiding using the disconnected warning option) it would be great

thanks

**Comment by starfi5h** [comment] 2023-01-22 11:05
Can you send me the save and a list of the mods you use?

**Comment by cyan** [comment] 2023-01-25 21:54
here a link to one of my last save
https://www.dropbox.com/s/1rpams45gsla429/Dyson%20sphere%20-%20cyan%20-%20Save.zip?dl=0

the mods i m actually using are (all those are managed by the r2modman client from thunderstore with BepInEx):
-Trash2sand
-BetterWarningIcons
-CraftMany
-RailgunsRetargetMini
-FactoryLocator (obviously)
-DSPStarMapMemo
-BottleNeck
-LSTM
-MoreStatInfo
-DSPStationInfo
-AutoLogisticsDroneSetup
-DSPAllPlanetInfo
-Planet_vein_Utilization
-NoHidingManualResearch
-ReorderTechQeue
-DSPMergeStorage
-MineralExhaustionNotifier
-PlanetFinder
-Max_Item_SAtack_Changer
-DSP_Drone_Clearing
-CruiseAssist
-BlueprintTweaks
-DSPGameSpeed
and what appear to be library needed by some mods
-DSPModSave
-CommonAPI
-NebulaMultiplayerModApi
-LDBTool

thanks

**Comment by starfi5h** [comment] 2023-01-26 18:18
The issue is now fixed in version 1.1.0. You should be able to remove those warnings using clear all button.

**Comment by cyan** [comment] 2023-01-26 22:14
the new version fixed the problem indeed, thanks a lot

**Closed as completed** 2023-01-26 22:15 UTC
Labels: bug
